### ISSUE TITLE
build failed, please help, thank you!

### ISSUE THREAD

**Issue by cmal** [knksmith57/hexo-renderer-sass#12]
I leave the log file as an attachment file of this comment, thanks!

**Comment by cmal** [comment]
[npm-debug.log.txt](https://github.com/knksmith57/hexo-renderer-sass/files/106427/npm-debug.log.txt)

**Comment by cmal** [comment]
[log.txt](https://github.com/knksmith57/hexo-renderer-sass/files/106434/log.txt)

**Comment by knksmith57** [comment]
Thanks for the bug submission! I'll do my best to check this out some time later today.

**Comment by JLHwung** [comment]
please run
```bash
chown -R `whoami` /Users/cmal/gits/hexo/themes/maupassant
```
and retry to see if it works.

**Comment by JLHwung** [comment]
Closed without reply after 14 days. Will re-open if replied.
