### ISSUE TITLE
Call for new maintainer

### ISSUE THREAD

**Issue by knksmith57** [knksmith57/hexo-renderer-sass#15]
Howdy everyone,

This project is used by quite a few people. Unfortunately, I don't use hexo anymore and this project has been neglected as a result.

I'm looking for someone willing to contribute proper love to the module and to take over the repo.

Any takers?

**Comment by jojoee** [comment]
Hi knksmith57,

I happy to contribute this project, but I think it's better to have you around.
So, in my opinion, creating organization will be suited
(also we can add more maintainers in the future).

How about your opinion ?

**Comment by JLHwung** [comment]
Hi knksmith57,
I am good to be a maintainer of this repository. I use hexo and hexo-renderer-sass for my theme.

**Comment by knksmith57** [comment]
Alright, so for the time being, I've added both @jojoee and @JLHwung as collaborators to this repo.

It might make more sense to move the project later, but for now I think this will suffice.

We'll get a CoC on here, but in the meantime, please be respectful and kind to other devs and _don't break semver_. 😉

Thanks!
