### ISSUE TITLE
display wrong in github pages

### ISSUE THREAD

**Issue by xueyouchao** [knksmith57/hexo-renderer-sass#16]
Hi, 
I used a theme using hexo-renderer-sass. It shows theme correctly on my local machine but wrong on github pages after hexo deploy.
So is it because hexo-renderer-sass is not supported by github pages?
Any solutions?

**Comment by JLHwung** [comment]
Hi xueyouchao,

Could you please tell us where is the github pages repository?

**Comment by xueyouchao** [comment]
I fixed it by adding exclude[] in the config file according to https://github.com/jekyll/jekyll/pull/5210
