### ISSUE TITLE
Roadmap discussion

### ISSUE THREAD

**Issue by JLHwung** [knksmith57/hexo-renderer-sass#19]
I have created a roadmap draft on https://github.com/knksmith57/hexo-renderer-sass/wiki/Roadmap. Please feel free to discuss on that.

Thank you.

cc @knksmith57 @jojoee

**Comment by knksmith57** [comment]
Love the draft and stoked with all the work and time you've put into this project in such a short amount of time. Thank you!

re: Code style, and I threw this comment in #23 but I'll iterate again here for posterity, I'd like to switch to using [`standard`](http://npm.im/standard) for code style. It keeps the checks simple, has built in "fix" support, and removes the possibility of ever discussing style specifics (eg: semicolons, tabs v spaces, etc etc).

**Comment by JLHwung** [comment]
@knksmith57 ping. Any plans on cutting 0.3.0 release?

**Comment by knksmith57** [comment]
@JLHwung how can I help?

**Comment by JLHwung** [comment]
Hi knksmith57,

I think we are ready to publish 0.3.0 to npm registry. Could you publish the package? Alternatively you could also add collaborators on npm.

Thank you.

**Comment by knksmith57** [comment]
Hey Junliang,

I just granted you collaborator access on npm. So long as you are comfortable, please feel free to cut the `0.3.0` release.

Thanks!

**Comment by JLHwung** [comment]
Hi Kyle,

Good to hear that, I will write some changelog and release in a few days.

**Comment by JLHwung** [comment]
resolved as 0.3 is landed.
