### ISSUE TITLE
Is it possible to add autoprefixer function?

### ISSUE THREAD

**Issue by Jim-Zenn** [knksmith57/hexo-renderer-sass#32]
Hi, thank you for maintaining the renderer. I recently switched from gulp to the renderer, it makes things easier.

However, the problem is that I used to use a autoprefixer, but with this plugin, it seems not possible to insert an autoprefixer.

Can this be added?

**Comment by Jim-Zenn** [comment]
#33 Pull request sent

**Comment by JLHwung** [comment]
I am sorry if it seems offending, but unfortunately we won't accept this feature request as it violates *do one thing and do it well* philosophy.

Please use [hexo-autoprefixer](https://github.com/hexojs/hexo-autoprefixer) as it works with `hexo-render-sass` seemlessly.

## TL;DR
Autoprefixer is a postcss plugin and use `autoprefixer` without `postcss` is deprecated if I remember correctly. So I change the feature request into adding `postcss` support to `hexo-renderer-sass`.

Hexo renderer is used to render a file/string into a format that browsers supports natively, namely JavaScript, CSS, HTML. Any post process of these files is modeled as a `after_render` filter, see https://github.com/hexojs/hexo-autoprefixer. Therefore, hexo-renderer-sass will not use `autoprefixer`, or more generally `postcss` inside render process as there should be a `hexo-filter-postcss` to do this job.

A renderer should *do one thing and do it well*. hexo-renderer-sass will only convert scss/sass to css and that's it. It is simply a wrapper on `node-sass` with minimal fallback configuration. It makes maintenance easy and debugging straightforward. However, adding `postcss` introduces extra complexity and the end user should determine whether he/she will use `postcss` on a simple sass/scss renderer while he/she could simply drop in `hexo-autoprefixer`.

**Comment by Jim-Zenn** [comment]
Wow thanks for letting me know this plugin exists! It does seems
inpropriate to add this then!

**Comment by JLHwung** [comment]
I am pleased to help. Closing now.
