### ISSUE TITLE
relative path in import

### ISSUE THREAD

**Issue by TrejGun** [knksmith57/hexo-renderer-sass#37]
hi there!
i have found a problem in loading scss files from node_modules

css files are fine
```
@import "~normalize.css";
@import "~normalize.css/normalize.css";
```
but scss files are not loading
```
@import "~bootstrap";
@import "~bootstrap/scss/bootstrap.scss";
```

i tried to add node-sass config

```
node_sass:
  includePaths:
   - node_modules
```
and it fixes imports from submodules
```
@import "bootstrap/scss/bootstrap.scss";
```
but "~" symbol still doesn't work
how can i configure this to work same as in `sass-loader`?

**Comment by JLHwung** [comment]
The tilde syntax is not a feature of `node-sass` but webpack. See https://github.com/webpack-contrib/css-loader/issues/12#issuecomment-41940311.

**Comment by TrejGun** [comment]
works like magic
